# Generated by Django 4.2.14 on 2024-09-05 11:37

from django.db import migrations, models
import emran.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Languages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_name", models.CharField(max_length=150)),
                ("language_description", models.CharField(max_length=500)),
                ("language_test_details", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Memberships",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("membership_name", models.CharField(max_length=150)),
                ("membership_type", models.CharField(max_length=150)),
                ("membership_organisation", models.CharField(max_length=500)),
                ("membership_institution", models.CharField(max_length=500)),
                ("membership_address", models.CharField(max_length=500)),
                ("membership_hasexpire", models.BooleanField()),
                ("membership_start_date", models.DateField()),
                ("membership_end_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Portfolios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("portflio_platform_name", models.CharField(max_length=150)),
                ("portflio_title", models.CharField(max_length=500)),
                ("portflio_description", models.TextField(blank=True, null=True)),
                ("portflio_link", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_position", models.CharField(max_length=150)),
                ("project_title", models.CharField(max_length=300)),
                ("project_description", models.TextField(blank=True, null=True)),
                (
                    "project_fund",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "project_funding_organisation",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "project_collaboration_organisation",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("project_start_date", models.DateField()),
                ("project_end_date", models.DateField(blank=True, null=True)),
                (
                    "project_image",
                    models.ImageField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=emran.models.get_organisation_upload_path,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionsOrEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_lead_name", models.CharField(max_length=150)),
                ("session_lead_type", models.CharField(max_length=150)),
                ("session_title", models.CharField(max_length=500)),
                ("session_description", models.TextField(blank=True, null=True)),
                ("session_organisation", models.CharField(max_length=500)),
                ("session_institution", models.CharField(max_length=500)),
                ("session_address", models.CharField(max_length=500)),
                ("session_start_date", models.DateField()),
            ],
        ),
    ]
