# Generated by Django 4.2.14 on 2024-09-05 11:48

from django.db import migrations, models
import emran.models


class Migration(migrations.Migration):

    dependencies = [
        ("emran", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificationsCoursesTrainings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cct_name", models.CharField(max_length=300)),
                ("cct_description", models.TextField(blank=True, null=True)),
                ("cct_offering_organisation", models.CharField(max_length=300)),
                (
                    "cct_funding_organisation",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("cct_key_information", models.TextField(blank=True, null=True)),
                ("cct_hasexpire", models.BooleanField()),
                ("cct_start_date", models.DateField()),
                ("cct_end_date", models.DateField(blank=True, null=True)),
                (
                    "cct_image",
                    models.ImageField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=emran.models.get_CertificationsCoursesTrainings_upload_path,
                    ),
                ),
                ("cct_online_credential", models.CharField(max_length=1000)),
            ],
        ),
    ]
