# Generated by Django 4.2.14 on 2024-11-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emran", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteering",
            name="volunteering_link",
            field=models.CharField(max_length=500),
        ),
    ]
