# Generated by Django 4.2.14 on 2024-09-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emran", "0002_certificationscoursestrainings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificationscoursestrainings",
            name="cct_online_credential",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
