# Generated by Django 4.2.14 on 2024-11-10 12:05

from django.db import migrations, models
import emran.models


class Migration(migrations.Migration):

    dependencies = [
        ("emran", "0002_alter_volunteering_volunteering_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteering",
            name="volunteering_image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=emran.models.get_CertificationsCoursesTrainings_upload_path,
            ),
        ),
    ]
