# Generated by Django 4.2.14 on 2024-09-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emran", "0003_alter_certificationscoursestrainings_cct_online_credential"),
    ]

    operations = [
        migrations.CreateModel(
            name="HonorsAndAwards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("haw_title", models.CharField(max_length=300)),
                ("haw_issuer_organisation", models.CharField(max_length=300)),
                ("haw_associated_organisation", models.CharField(max_length=300)),
                ("haw_start_date", models.DateField()),
                ("haw_short_description", models.CharField(max_length=300)),
                ("haw_description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
