# Generated by Django 4.2.14 on 2024-11-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emran", "0004_keyinformation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pub_type", models.CharField(max_length=300)),
                ("pub_subtype", models.CharField(max_length=300)),
                ("pub_title", models.CharField(max_length=500)),
                ("pub_citation", models.CharField(max_length=1000)),
                ("pub_doi_or_link", models.CharField(max_length=500)),
                ("pub_abstract", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
