# Generated by Django 4.2.14 on 2024-09-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emran", "0004_honorsandawards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="honorsandawards",
            name="haw_associated_organisation",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
