# Generated by Django 4.2.14 on 2024-11-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emran", "0005_publications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publications",
            name="pub_subtype",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
