# Generated by Django 4.2.14 on 2024-09-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emran", "0006_skillsandtools"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificationscoursestrainings",
            name="cct_type",
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
