# Generated by Django 4.2.14 on 2024-11-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emran", "0006_alter_publications_pub_subtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="publications",
            name="pub_serial_no",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
