# Generated by Django 4.2.14 on 2024-09-06 22:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("emran", "0007_certificationscoursestrainings_cct_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificationscoursestrainings",
            name="cct_type",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("all", "All"),
                    ("certificate", "Certificate"),
                    ("training", "Training"),
                    ("course", "Course"),
                ],
                default="all",
                max_length=31,
            ),
        ),
    ]
