# Generated by Django 4.2.14 on 2024-11-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emran", "0008_contacts"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pi_name", models.CharField(max_length=300)),
                (
                    "pi_hr_fields",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "pi_hr_affiliations",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "pi_hr_work_areas",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "pi_sm_linkedin",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "pi_sm_twitter",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "pi_sm_facebook",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "pi_sm_instagram",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "pi_sm_email",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "pi_sm_phone",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "pi_sm_skype",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "pi_sm_googlescholar",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "pi_sm_researchgate",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "pi_sm_github",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "pi_sm_stackoverflow",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "pi_sm_quora",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "pi_sm_youtube",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("si_website", models.CharField(max_length=500)),
                ("si_about", models.CharField(max_length=500)),
                ("si_name", models.CharField(max_length=600)),
                ("si_copyright", models.CharField(max_length=200)),
                ("si_version", models.CharField(max_length=100)),
                ("si_year", models.IntegerField()),
                ("si_description", models.CharField(max_length=600)),
                ("si_con_location", models.CharField(max_length=500)),
                ("si_con_map_link", models.CharField(max_length=1000)),
                ("si_phone", models.CharField(max_length=500)),
                ("si_email", models.CharField(max_length=500)),
                ("si_skype", models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name="contacts",
            old_name="con_map_link",
            new_name="con_name",
        ),
        migrations.RemoveField(
            model_name="contacts",
            name="con_loc",
        ),
        migrations.RemoveField(
            model_name="contacts",
            name="con_phone",
        ),
        migrations.RemoveField(
            model_name="contacts",
            name="con_skype",
        ),
        migrations.AddField(
            model_name="contacts",
            name="con_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contacts",
            name="con_subject",
            field=models.CharField(default="test", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contacts",
            name="con_email",
            field=models.CharField(default="test@sf.d", max_length=500),
            preserve_default=False,
        ),
    ]
