# Generated by Django 4.2.14 on 2024-11-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emran", "0009_personalinformation_siteinformation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinformation",
            name="pi_hr_affiliations",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
