# Generated by Django 4.2.14 on 2024-11-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emran", "0010_alter_personalinformation_pi_hr_affiliations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteinformation",
            name="si_about",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="siteinformation",
            name="si_description",
            field=models.TextField(max_length=5000),
        ),
    ]
