# Generated by Django 4.2.14 on 2024-11-21 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emran", "0011_alter_siteinformation_si_about_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="siteinformation",
            old_name="si_copyright",
            new_name="si_cr_copyright",
        ),
        migrations.RenameField(
            model_name="siteinformation",
            old_name="si_description",
            new_name="si_cr_description",
        ),
        migrations.RenameField(
            model_name="siteinformation",
            old_name="si_version",
            new_name="si_cr_version",
        ),
        migrations.RenameField(
            model_name="siteinformation",
            old_name="si_year",
            new_name="si_cr_year",
        ),
        migrations.AddField(
            model_name="siteinformation",
            name="si_cr_name",
            field=models.CharField(
                default=datetime.datetime(
                    2024, 11, 21, 13, 56, 38, 949032, tzinfo=datetime.timezone.utc
                ),
                max_length=600,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="siteinformation",
            name="si_name",
            field=models.CharField(max_length=500),
        ),
    ]
