# Generated by Django 4.2.14 on 2024-12-19 08:28

from django.db import migrations, models
import emran.models


class Migration(migrations.Migration):

    dependencies = [
        ("emran", "0013_siteinformation_si_hero_image1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteinformation",
            name="si_hero_image1",
            field=models.ImageField(
                max_length=500,
                null=True,
                upload_to=emran.models.get_SiteInformation_HeroBG_upload_path,
            ),
        ),
    ]
