# Generated by Django 4.2.14 on 2024-12-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emran", "0014_alter_siteinformation_si_hero_image1"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinformation",
            name="pi_sm_whatsapp",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
